name: build website # ThankYou @tomkralidis!

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: build website
        run: npm run build

      - name: Setup Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.event_name == 'push'
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4