# Thanks @tomkralidis!

name: build website

on:
  push:
    branches:
    - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  checkout repo
        uses: actions/checkout@v4

      - name:  setup NodeJS
        uses: actions/setup-node@v4

      - name:  install dependencies
        run:  |
            npm install

      - name: build website
        run: |
          npm run build
          mv dist/ /tmp

      - name: checkout gh-pages branch
        uses: actions/checkout@v4
        with:
            ref: gh-pages

      - name: update gh-pages branch and publish
        run: | 
          git config --global user.email "doublebyte@hushmail.com"
          git config --global user.name "doublebyte1"
          rm -rf assets css js index.html
          mv -f /tmp/dist/* .
          git add .
          git commit -am "update website"
          git push
